### ISSUE TITLE
using esp8266-12e

### ISSUE THREAD

**Issue by alinelena** [aromring/MAX30102_by_RF#20] opened 2020-08-23 13:45 UTC
I try to get the code working with esp8266-12e. I assume the hardware is ok... tested with esp32 and followed #13 to determine the leds are swapped...but other than that seems to work correctly, at least if you have warm hands.

issues to build, the ones mentioned in #19 plus the need to have (all happens on a linux, plarform io) 

```
void millis_to_hours(uint32_t ms, char* hr_str);
#ifdef USE_ADALOGGER
// blink three times if isOK is true, otherwise blink continuously
void blinkLED(const byte led, bool isOK)
#endif
```

before setup()
====

now success finishes here enabling debug I endup with the same numbers as shown below. looks to me like detection of presence does not work... any help appreciated.
int is connected to gpio12 that is d6, sda on d2, scl on d1

```
--RF--
40      80.14   125     0:0:40
------
40      80.14   125     0:0:40  1.00    1.00
0       196351  196351
1       196351  196351
2       196351  196351
3       196351  196351
4       196351  196351
5       196351  196351
6       196351  196351
7       196351  196351
8       196351  196351
9       196351  196351
10      196351  196351
11      196351  196351
12      196351  196351
13      196351  196351
14      196351  196351
15      196351  196351
16      196351  196351
17      196351  196351
18      196351  196351
19      196351  196351
20      196351  196351
21      196351  196351
22      196351  196351
23      196351  196351
24      196351  196351
25      196351  196351
26      196351  196351
27      196351  196351
28      196351  196351
29      196351  196351
30      196351  196351
31      196351  196351
32      196351  196351
33      196351  196351
34      196351  196351
35      196351  196351
36      196351  196351
37      196351  196351
38      196351  196351
39      196351  196351
40      196351  196351
41      196351  196351
42      196351  196351
43      196351  196351
44      196351  196351
45      196351  196351
46      196351  196351
47      196351  196351
48      196351  196351
49      196351  196351
50      196351  196351
51      196351  196351
52      196351  196351
53      196351  196351
54      196351  196351
55      196351  196351
56      196351  196351
57      196351  196351
58      196351  196351
59      196351  196351
60      196351  196351
61      196351  196351
62      196351  196351
63      196351  196351
64      196351  196351
65      196351  196351
66      196351  196351
67      196351  196351
68      196351  196351
69      196351  196351
70      196351  196351
71      196351  196351
72      196351  196351
73      196351  196351
74      196351  196351
75      196351  196351
76      196351  196351
77      196351  196351
78      196351  196351
79      196351  196351
80      196351  196351
81      196351  196351
82      196351  196351
83      196351  196351
84      196351  196351
85      196351  196351
86      196351  196351
87      196351  196351
88      196351  196351
89      196351  196351
90      196351  196351
91      196351  196351
92      196351  196351
93      196351  196351
94      196351  196351
95      196351  196351
96      196351  196351
97      196351  196351
98      196351  196351
99      196351  196351
--RF--
40      80.14   125     0:0:40
------
40      80.14   125     0:0:40  1.00    1.00
```

**Comment by aromring** [comment] 2020-08-24 17:51
You may have a faulty sensor that does not produce any signal.
Yours is not a bug report of the algorithm and does not belong here, on GitHub, but in related hardware forums. I going to leave it on for some time, though, so that others who have experience with esp8266-12e can comment. After that I am going to close it.

**Comment by alinelena** [comment] 2020-08-25 10:52
@aromring the sensor works correctly with esp32 and your code. Except the swapped RED/IR leds, I have no issue with it when used with esp32.
Also the esp8266 works as expected, so I will remove the defective hw hypothesis. 
it is just a matter of porting the code to other hw.

**Comment by aromring** [comment] 2020-08-28 00:45
Perhaps you are right. Neither I have heard about, nor used esp8266-12e, thus I can't help you with porting the code.

**Closed as completed** 2020-09-12 17:51 UTC
